# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [99]:
nullVector = np.zeros((10))
nullVector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [100]:
x=np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [101]:
x.shape

(40,)

5. Print the type of the previous array in question 3

In [102]:
x.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [103]:
print (f"numpy version is: {np.__version__} \n")
print(np.show_config())

numpy version is: 1.19.2 

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
None


7. Print the dimension of the array in question 3


In [104]:
x.ndim

1

8. Create a boolean array with all the True values

In [105]:
bol_arr=np.full((5), True)
bol_arr

array([ True,  True,  True,  True,  True])

9. Create a two dimensional array




In [106]:
ar = np.array([[4,2,8],[7,9,6]])
ar

array([[4, 2, 8],
       [7, 9, 6]])

10. Create a three dimensional array



In [9]:
arr = np.ones((3,3,4))
arr

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
list =[2,53,2,14,35,5,56,45,23]
vc = np.array(list)
print(f" Original vector: {vc}")
print(f"Reversed Vector: {np.flip(vc)}")

 Original vector: [ 2 53  2 14 35  5 56 45 23]
Reversed Vector: [23 45 56  5 35 14  2 53  2]


12. Create a null vector of size 10 but the fifth value which is 1 

In [109]:
vctr = np.zeros(10)
vctr[4]=1
vctr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [110]:
identity=np.identity(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [13]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr.astype('float16')
arr.dtype

dtype('float16')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [16]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [115]:
arr1 = np.array([[1., 2., 3.],
                     [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],
                     [7., 2., 12.]])
comparr = np.maximum(arr1,arr2)
comparr

array([[ 1.,  4.,  3.],
       [ 7.,  5., 12.]])

17. Extract all odd numbers from arr with values(0-9)

In [20]:
arr = np.arange(0,10)
arr[1:10:2] #by slicing the array

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [21]:
arr[1:10:2]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [23]:
arr= np.arange(10)
arr[5:9] =12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [41]:
arr1= np.ones((8,8))
arr1[1:7,1:7]=0
arr1

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [43]:
arr2d = np.array([[1, 2, 3],
            [4, 5, 6], 
            [7, 8, 9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [46]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,0]=64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [72]:
ar = np.arange(10)
ar = ar.reshape(5,2)
print(f"arra before slicing is \n {ar}\n")
print(f"slicing of the above array is \n {ar[0:1]}")

arra before slicing is 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

slicing of the above array is 
 [[0 1]]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [105]:
arr2nd = np.arange(10).reshape(2,5)
print(f" 2nd value from 2nd 1-D array from above array is: {arr2nd[1:2,1:2]}")

 2nd value from 2nd 1-D array from above array is: [[6]]


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [129]:
arr = np.arange(10).reshape(2,5)
arr[0:2,2:3]

array([[2],
       [7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [130]:
rndArray = np.random.rand(10,10)
print(f"Maximum value from the array is: {np.max(rndArray)}")
print(f"Minimum value from the array is: {np.min(rndArray)}")

Maximum value from the array is: 0.9983659262838563
Minimum value from the array is: 0.018868594220132873


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [138]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [143]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.where(np.equal(a,b))
c

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [145]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)

array([[-0.43133724,  0.11737994,  1.147162  , -0.36941501],
       [-1.50630807, -0.61238237,  0.26090763,  0.33524898],
       [ 0.09719658, -1.86039321, -0.25643576, -0.92848087],
       [-1.68828389, -1.55100683,  2.0667169 , -1.06280798],
       [-0.24131181,  0.89742103, -1.05126331,  1.19236345],
       [ 0.778275  ,  0.27435588,  0.45694773,  1.01993958],
       [ 1.4784494 , -1.16036117, -0.60627892, -1.31196236]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [151]:
arr = np.arange(1,16, dtype="float16").reshape(5,3)
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]], dtype=float16)

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [155]:
arr1 = np.arange(1,17, dtype="float16").reshape(2,2,4)
arr1

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]], dtype=float16)

33. Swap axes of the array you created in Question 32

In [160]:
arr1.swapaxes(2,1)

array([[[ 1.,  5.],
        [ 2.,  6.],
        [ 3.,  7.],
        [ 4.,  8.]],

       [[ 9., 13.],
        [10., 14.],
        [11., 15.],
        [12., 16.]]], dtype=float16)

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [196]:
arr = np.random.rand(10)
sq_arr= np.sqrt(arr)
sq_arr[sq_arr<0.5]=0
sq_arr

array([0.73361964, 0.96030569, 0.64860292, 0.65070175, 0.        ,
       0.80629187, 0.92175601, 0.        , 0.70653129, 0.57340723])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [199]:
arr1 = np.random.rand(12)
arr2 = np.random.rand(12)
np.maximum(arr1,arr2)

array([0.83620663, 0.99848552, 0.55779899, 0.82589558, 0.60191642,
       0.97374646, 0.43906833, 0.48440143, 0.55071429, 0.6717239 ,
       0.75761989, 0.13983672])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [205]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.sort(np.unique(names))

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [210]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
a = np.setdiff1d(a,b)
a

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [242]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10],[10],[10]])
print(sampleArray)
sampleArray =np.delete(sampleArray,1,1)
print(f"column deleted\n{sampleArray}")
sampleArray = np.append(sampleArray, newColumn,1)
sampleArray



[[34 43 73]
 [82 22 12]
 [53 94 66]]
column deleted
[[34 73]
 [82 12]
 [53 66]]


array([[34, 73, 10],
       [82, 12, 10],
       [53, 66, 10]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [246]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [248]:
x = np.random.rand(20)
np.cumsum(x)

array([0.23173197, 0.65761579, 1.11041954, 1.66009628, 2.08212886,
       2.96384986, 3.002036  , 3.31624823, 3.77291867, 4.3354613 ,
       4.77009905, 4.91140685, 5.20775604, 5.4752478 , 6.3482125 ,
       6.7076558 , 6.93175289, 7.01530647, 7.26228272, 8.20136735])