# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np

arr = np.arange(0, 10)
print(arr)
arr = arr.reshape(2, 5)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
arr1 = np.array([np.arange(0, 5), np.arange(5, 10)], dtype = 'int32')
arr2 = np.array([np.ones(5), np.ones(5)], dtype = 'int32')
np.vstack((arr1, arr2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:
np.hstack((arr1, arr2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [4]:
arr2d = np.array([np.arange(0, 5), np.arange(5, 10)], dtype = 'int32')
arr2d = arr2d.reshape(10)
print(arr2d)

[0 1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [5]:
arr3d = np.array([[[0,1,2,3], [4,5,6,7]], [[8,9,10,11], [12,13,14,15]]])
arr3d = arr3d.reshape(-1)
print(arr3d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [6]:
arr1d = np.arange(0, 15, dtype = 'int32')
arr1d.reshape(5, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [7]:
arr = np.arange(1, 26).reshape(5,5)
print(arr, end = "\n\n")
print(np.square(arr))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]
 [256 289 324 361 400]
 [441 484 529 576 625]]


## Question:8

### Create 5x6 an array and find the mean?

In [8]:
arr = np.arange(0, 30).reshape(5, 6)
print(arr, end = '\n\n')
print(np.mean(arr))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [9]:
np.std(arr)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [10]:
np.median(arr)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [11]:
np.transpose(arr)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [12]:
arr = np.arange(0, 16).reshape(4,4)
print(arr, end = '\n\n')
print(np.trace(arr))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

30


## Question:13

### Find the determinant of the previous array in Q12?

In [13]:
print(np.linalg.det(arr))

0.0


## Question:14

### Find the 5th and 95th percentile of an array?

In [14]:
arr = np.arange(0, 15)
print(arr, np.percentile(arr, 5), np.percentile(arr, 95), sep = '\n')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
0.7000000000000001
13.299999999999999


## Question:15

### How to find if a given array has any null values?

In [15]:
arrNull = np.NaN
print(np.isnan(arrNull), sep = '\n')

True
