# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
vec = np.zeros(10)
print(vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [3]:
vec = np.arange(10, 50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [4]:
print(vec.shape)

(40,)


5. Print the type of the previous array in question 3

In [5]:
print(vec.dtype)

int32


6. Print the numpy version and the configuration


In [6]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


7. Print the dimension of the array in question 3


In [7]:
print(vec.ndim)

1


8. Create a boolean array with all the True values

In [8]:
boolArr = np.ones(7, dtype = bool)
print(boolArr)

[ True  True  True  True  True  True  True]


9. Create a two dimensional array




In [9]:
arr2d = np.array([[1,2,3], [2,4,6]])
print(arr2d)

[[1 2 3]
 [2 4 6]]


10. Create a three dimensional array



In [10]:
arr3d = np.array([[[1,2,3], [2,4,6], [3,5,7]]])
print(arr3d)

[[[1 2 3]
  [2 4 6]
  [3 5 7]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
vec = np.arange(1, 16)
vec = np.flip(vec)
print(vec)

[15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
vec = np.zeros(10)
vec.put(4, 1)
print(vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [13]:
imatrix = np.identity(3)
print(imatrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1,2,3,4,5])
arr = arr.astype(np.float)
print(arr.dtype)

float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1.,2.,3.], [4.,5.,6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(np.multiply(arr1, arr2))

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1.,2.,3.], [4.,5.,6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
newArr = arr1 == arr2
print(newArr)

[[False False False]
 [False False False]]


17. Extract all odd numbers from arr with values(0-9)

In [17]:
arr = np.arange(0, 9)
print(arr[arr % 2 == 1])

[1 3 5 7]


18. Replace all odd numbers to -1 from previous array

In [18]:
arr = np.where(arr % 2 == 1, -1, arr)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)

for i in range (5, 9):
    arr.put(i, 12)
    
print(arr)

[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [20]:
arr = np.zeros((2, 2))
arr = np.pad(arr, 1, mode = 'constant', constant_values = 1)
print(arr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d = np.where(arr2d == 5, 12, arr2d)
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for i in arr3d[0, 0] - 1:
    arr3d[0, 0, i] = 64
    
print(arr3d)

[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
arr2d = np.array([np.arange(0, 5), np.arange(5, 10)])
print(arr2d[0])
print(arr2d[0, 1:])

[0 1 2 3 4]
[1 2 3 4]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
arr2d = np.array([np.arange(0, 5), np.arange(5, 10)])
print(arr2d[1:,1 ])

[6]


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
arr2d = np.array([np.arange(0, 5), np.arange(5, 10)])
print(arr2d[0:,2 ])

[2 7]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
randArr = np.random.rand(10, 10)
print("Minimum Value: ", np.min(randArr))
print("Maximum Value: ", np.max(randArr))

Minimum Value:  0.007953280922150086
Maximum Value:  0.9756919662524061


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(np.in1d(a, b))

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data[names!='Will']
print(names, data, sep = '\n')

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 1.16316753 -1.60944155  2.35050619  0.30839565]
 [-0.17509664 -0.06293153  0.12451091 -0.55755282]
 [-0.01402865  1.03602056  0.07451534  0.59124974]
 [-0.55398334 -0.81236586  0.53284047  0.37917654]
 [ 0.271077   -0.74951147 -2.16037785 -0.25282574]
 [ 0.84421878 -1.78051569  0.43832108  0.77692396]
 [-1.22859054  0.69512817 -0.59523568 -0.01769877]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

print(data, end = '\n\n')
data[(names != 'Will') & (names != 'Joe')]

[[-1.26482897  1.93969672  1.32298151 -1.43105446]
 [ 0.55650249 -1.19233085  0.032221   -0.79674565]
 [-0.62870089  0.34644778  0.50996069 -0.95574015]
 [-1.01855992 -1.71933295  0.62058014 -0.26630205]
 [ 0.5220204   0.58768554  1.69732182 -0.74784634]
 [ 0.37770538  0.32087583 -1.35613235 -0.53718552]
 [ 1.05203236  0.77485103  1.41191605 -0.06225381]]



array([[-1.26482897,  1.93969672,  1.32298151, -1.43105446],
       [-1.01855992, -1.71933295,  0.62058014, -0.26630205]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
arr = np.arange(1.1, 15, 0.99).reshape(5, 3)
print(arr)

[[ 1.1   2.09  3.08]
 [ 4.07  5.06  6.05]
 [ 7.04  8.03  9.02]
 [10.01 11.   11.99]
 [12.98 13.97 14.96]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:
arr = np.arange(1.1, 16, 0.99).reshape(2,2,4)
print(arr)

[[[ 1.1   2.09  3.08  4.07]
  [ 5.06  6.05  7.04  8.03]]

 [[ 9.02 10.01 11.   11.99]
  [12.98 13.97 14.96 15.95]]]


33. Swap axes of the array you created in Question 32

In [33]:
arr = arr = np.arange(1.1, 16, 0.99).reshape(2,2,4)

print("Normal: \n", arr)

arr = np.swapaxes(arr, 0, 2)

print("Swapped: \n", arr)

Normal: 
 [[[ 1.1   2.09  3.08  4.07]
  [ 5.06  6.05  7.04  8.03]]

 [[ 9.02 10.01 11.   11.99]
  [12.98 13.97 14.96 15.95]]]
Swapped: 
 [[[ 1.1   9.02]
  [ 5.06 12.98]]

 [[ 2.09 10.01]
  [ 6.05 13.97]]

 [[ 3.08 11.  ]
  [ 7.04 14.96]]

 [[ 4.07 11.99]
  [ 8.03 15.95]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [34]:
arr = np.random.rand(10)
sqrtArr = np.sqrt(arr)

sqrtArr[sqrtArr < 0.5] = 0

print(sqrtArr)

[0.         0.         0.84803696 0.51401864 0.         0.6151184
 0.90823122 0.         0.72893724 0.79629179]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [35]:
arr1 = np.random.rand(4, 3)
arr2 = np.random.rand(4, 3)

print(np.maximum(arr1, arr2))

[[0.54538716 0.78829305 0.49220355]
 [0.75907479 0.66237733 0.59605978]
 [0.97024054 0.5438862  0.60821976]
 [0.86641983 0.2715399  0.69671492]]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

uniqueNames = np.unique(names)
uniqueNames.sort(-1)

print(uniqueNames)

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [37]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.where(a != b)

(array([0, 1, 2, 3, 4], dtype=int64),)

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [38]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = np.array([[10,10,10]])

sampleArray[:, 1] = newColumn
print(sampleArray)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [39]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [40]:
rMatrix = np.random.rand(5,4)
print(rMatrix)
print("Cumulative Sum of Matrix: ", np.cumsum(rMatrix))

[[0.86996138 0.68528176 0.47146297 0.64486818]
 [0.23549462 0.06282692 0.49774172 0.22269289]
 [0.61255162 0.596022   0.27769556 0.53251004]
 [0.14139387 0.1772811  0.0500299  0.70954893]
 [0.83990515 0.0655161  0.23682675 0.13901205]]
Cumulative Sum of Matrix:  [0.86996138 1.55524313 2.0267061  2.67157428 2.9070689  2.96989582
 3.46763755 3.69033044 4.30288206 4.89890405 5.17659962 5.70910965
 5.85050352 6.02778463 6.07781453 6.78736346 7.62726861 7.69278471
 7.92961146 8.06862351]
