# **Assignment For Numpy By Hammad Ahmed **

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [3]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
np.zeros(10)


10

3. Create a vector with values ranging from 10 to 49

In [6]:
x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [7]:
np.shape(x)

(40,)

5. Print the type of the previous array in question 3

In [21]:
x.dtype

dtype('int64')

6. Print the numpy version and the configuration


In [7]:
print(np.__version__)
print(np.show_config())

1.19.4
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/srv/conda/envs/notebook/lib']
    include_dirs = ['/srv/conda/envs/notebook/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/srv/conda/envs/notebook/lib']
    include_dirs = ['/srv/conda/envs/notebook/include']
    language = c
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['/srv/conda/envs/notebook/lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/srv/conda/envs/notebook/lib']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/srv/conda/envs/notebook/include']
None


7. Print the dimension of the array in question 3


In [20]:
np.ndim(x)

1

8. Create a boolean array with all the True values

In [30]:
np.array([True,True,True])

dtype('bool')

9. Create a two dimensional array




In [23]:
np.array([[2,2],[3,5]])

array([[2, 2],
       [3, 5]])

10. Create a three dimensional array



In [24]:
np.array([[[3,5,8],[6,8,9],[3,7,9]]])

array([[[3, 5, 8],
        [6, 8, 9],
        [3, 7, 9]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [10]:
x= np.array([1,2,4,7,9])
np.flip(x)

array([9, 7, 4, 2, 1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [33]:
x=np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [5]:
np.random.randn(3,3)


array([[-1.4232844 ,  0.34223193, -0.89502586],
       [ 2.37328319, -0.67329606, -2.49552022],
       [ 1.36936185, -0.32815139, -0.14396611]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [2]:
arr = np.array([1, 2, 3, 4, 5]) 

float_array = arr.astype(float)

float_array

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [35]:


    arr1 = np.array([[1., 2., 3.],

                [4., 5., 6.]])  

    arr2 = np.array([[0., 4., 1.],

               [7., 2., 12.]])


arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [15]:


    arr1 = np.array([[1., 2., 3.],

                [4., 5., 6.]]) 

    arr2 = np.array([[0., 4., 1.],

                [7., 2., 12.]])


arr1 == arr2

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [3]:
arr = np.arange(0,10)
x=arr[1:10:2]
x

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [4]:
x[:]=-1

x


array([-1, -1, -1, -1, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [48]:
arr = np.arange(10)
arr[5]=12
arr[6]=12
arr[7]=12
arr[8]=12

20. Create a 2d array with 1 on the border and 0 inside

In [5]:
arr=np.array([[1,1,1,1,1,1],[1,1,1,1,1,1],[1,1,1,1,1,1],[1,1,1,1,1,1]])

arr[1:3,1:5]=0

arr

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [6]:
arr2d = np.array([[1, 2, 3],
                [4, 5, 6], 
                [7, 8, 9]])

arr2d[1:2,1:2]=12

arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [7]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr3d[0:1]=64

arr3d


array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [8]:
x=np.array([[0,1,2,3,4],[5,6,7,8,9]])

x[0:1,0:1]

array([[0]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [10]:
x=np.array([[0,1,2,3,4],[5,6,7,8,9]])

x[1:2,1:2]

array([[6]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [12]:
x=np.array([[0,1,2,3,4],[5,6,7,8,9]])

x[0:2,2:3]

array([[2],
       [7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [19]:
x= np.random.randn(10,10)
max1=np.max(x)
min1 = np.min(x)
print(x)
print("Maximium",max1)
print("Minimum",min1)


[[ 2.16987276  0.19375084 -0.07363549 -1.03216309  0.23977984 -1.38109582
   1.39291172 -0.17354836  0.89949707 -0.21277664]
 [ 0.54252129 -0.54430365 -0.44409458  0.57192178 -0.93777417 -1.18068796
  -0.41427534  0.2348656  -2.0782263   0.8368014 ]
 [ 0.96247078 -1.41099447 -0.17987281 -1.32025707 -1.39963702  3.21479211
   0.88359527 -0.27916579  0.15491424 -1.1901312 ]
 [ 0.87098989  1.26083897 -0.92264743 -0.01601655 -1.14709301 -1.64493687
  -0.46411646 -0.98299225  0.2539826   0.32476938]
 [-0.36678043  0.24183208 -0.75101253 -1.30844719  1.31433629 -0.63223062
   1.1935515   0.52096178  0.35041655 -0.24542593]
 [-1.22308998 -0.3689774   2.23967154  0.20207704  0.6901972   0.55523682
  -1.94409888 -0.3097753   0.60612793 -0.10300152]
 [-0.80580431  0.81450102  0.9425005  -0.02061455 -0.24429827  0.67758852
   1.18141448  1.01303802 -1.64979198 -0.48075435]
 [-0.0963355   1.43570051 -0.22018012  0.01024121  0.01650657 -0.66563963
   0.56460305  1.05248117  0.25531655 -0.11770365]


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [17]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b) 

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [9]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
x= a==b


array([[False,  True, False,  True, False,  True, False,  True, False,
        False]])

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [22]:
data = np.random.randn(7, 4)
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
x= names != 'Bob'
data[(x)]

array([[-0.17899126,  1.11428127,  0.42812087,  0.49845559],
       [-0.89767335, -1.1167566 , -0.93841489, -0.4474496 ],
       [ 0.05565927, -0.46740943, -0.2562496 , -0.54110452],
       [ 1.43243747,  0.30099458, -0.13751162, -0.42559085],
       [ 0.24624852,  0.18960584,  0.65690464,  0.7953139 ]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [25]:
data = np.random.randn(7, 4)
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
x = names != 'Bob' 
p = names != 'Joe'
data[(x & p)]

array([[-0.62355654,  0.45823864,  1.505721  ,  0.46508389],
       [ 0.75106408,  1.11920173, -0.37721772, -1.23016625]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [57]:
np.random.rand(5, 3)*10

array([[5.88487003, 6.79487369, 7.89297125],
       [4.27472435, 7.38265421, 0.65942271],
       [3.96880238, 8.86068745, 9.64375251],
       [9.18575044, 2.42428509, 0.29543754],
       [2.14107171, 4.44268967, 8.11462945]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [77]:
c = np.arange(16).reshape(2,2,4)   

print(c)
??

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


33. Swap axes of the array you created in Question 32

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [88]:
x=np.arange(0,10)
p= np.sqrt(x)
np.where(p<0.5, 0, x)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [17]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
x=np.unique(names)
x.sort()
x

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [95]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
a = np.delete(a, np.where(a==5))

print(a)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [39]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = np.array([[10,10,10]])
sampleArray[1:2,:]=newColumn
sampleArray

array([[34, 43, 73],
       [10, 10, 10],
       [53, 94, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [32]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [4]:
x= np.random.randn(20)
print(x)
x.cumsum()

[-1.52847692 -0.71873792  0.38951467 -0.5026471   0.93833661  1.5633341
 -0.1587363   0.76727933 -0.05141191  0.80527917  0.60860871  1.48616751
 -0.19092359  0.89969887 -0.01491925  0.80020717  0.45361574 -0.93528931
  0.20741666 -2.53057951]


array([-1.52847692, -2.24721484, -1.85770017, -2.36034726, -1.42201065,
        0.14132345, -0.01741285,  0.74986648,  0.69845457,  1.50373374,
        2.11234245,  3.59850996,  3.40758637,  4.30728524,  4.292366  ,
        5.09257317,  5.54618892,  4.6108996 ,  4.81831626,  2.28773675])